'use strict';
export default {

    // Parser
    parser: '@typescript-eslint/parser',
    parserOptions: {
        sourceType: 'module',
        ecmaVersion: 'esnext',
    },

    // External
    plugins: [
        '@typescript-eslint',
    ],
    extends: [],

    // Variables
    env: {
        'browser': true,
        'es6': true,
    },
    globals: {},

    // Rules
    rules: {}
};
